[package]
name = "rolling-delta"
version = "0.1.0"
edition = "2021"


[lib]
name = "rolling_delta"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
derive_more = "0.99.17"